import json

data = """
https://onepiece.fandom.com/wiki/Monkey_D._Luffy, Easy
https://onepiece.fandom.com/wiki/Roronoa_Zoro, Easy
https://onepiece.fandom.com/wiki/Nami, Easy
https://onepiece.fandom.com/wiki/Sanji, Easy
https://onepiece.fandom.com/wiki/Trafalgar_D._Water_Law, Easy
https://onepiece.fandom.com/wiki/Nico_Robin, Easy
https://onepiece.fandom.com/wiki/Boa_Hancock, Easy
https://onepiece.fandom.com/wiki/Carrot, Easy
https://onepiece.fandom.com/wiki/Portgas_D._Ace, Easy
https://onepiece.fandom.com/wiki/Sabo, Easy
https://onepiece.fandom.com/wiki/Yamato, Easy
https://onepiece.fandom.com/wiki/Shanks, Easy
https://onepiece.fandom.com/wiki/Donquixote_Rosinante, Easy
https://onepiece.fandom.com/wiki/Charlotte_Katakuri, Easy
https://onepiece.fandom.com/wiki/Usopp, Easy
https://onepiece.fandom.com/wiki/Tony_Tony_Chopper, Easy
https://onepiece.fandom.com/wiki/Crocodile, Easy
https://onepiece.fandom.com/wiki/Jinbe, Easy
https://onepiece.fandom.com/wiki/Marco, Easy
https://onepiece.fandom.com/wiki/Donquixote_Doflamingo, Easy
https://onepiece.fandom.com/wiki/Nefertari_Vivi, Easy
https://onepiece.fandom.com/wiki/Bentham, Easy
https://onepiece.fandom.com/wiki/Eustass_Kid, Easy
https://onepiece.fandom.com/wiki/Kozuki_Oden, Easy
https://onepiece.fandom.com/wiki/Perona, Medium
https://onepiece.fandom.com/wiki/Brook, Easy
https://onepiece.fandom.com/wiki/Smoker, Easy
https://onepiece.fandom.com/wiki/Franky, Easy
https://onepiece.fandom.com/wiki/Gol_D._Roger, Easy
https://onepiece.fandom.com/wiki/Dracule_Mihawk, Easy
https://onepiece.fandom.com/wiki/Edward_Newgate, Easy
https://onepiece.fandom.com/wiki/Going_Merry, Hard
https://onepiece.fandom.com/wiki/Silvers_Rayleigh, Easy
https://onepiece.fandom.com/wiki/Buggy, Easy
https://onepiece.fandom.com/wiki/Enel, Easy
https://onepiece.fandom.com/wiki/Kuzan, Easy
https://onepiece.fandom.com/wiki/Woop_Slap, Hard
https://onepiece.fandom.com/wiki/Tashigi, Medium
https://onepiece.fandom.com/wiki/Vinsmoke_Reiju, Medium
https://onepiece.fandom.com/wiki/Bartolomeo, Medium
https://onepiece.fandom.com/wiki/X_Drake, Medium
https://onepiece.fandom.com/wiki/Koby, Medium
https://onepiece.fandom.com/wiki/Rob_Lucci, Easy
https://onepiece.fandom.com/wiki/Monkey_D._Garp, Easy
https://onepiece.fandom.com/wiki/Charlotte_Pudding, Medium
https://onepiece.fandom.com/wiki/Marshall_D._Teach, Easy
https://onepiece.fandom.com/wiki/Kikunojo, Medium
https://onepiece.fandom.com/wiki/Izou, Medium
https://onepiece.fandom.com/wiki/Kozuki_Hiyori, Medium
https://onepiece.fandom.com/wiki/Shirahoshi, Medium
https://onepiece.fandom.com/wiki/Pell, Medium
https://onepiece.fandom.com/wiki/Issho, Medium
https://onepiece.fandom.com/wiki/Sakazuki, Easy
https://onepiece.fandom.com/wiki/Tama, Medium
https://onepiece.fandom.com/wiki/Killer, Medium
https://onepiece.fandom.com/wiki/Ulti, Medium
https://onepiece.fandom.com/wiki/Benn_Beckman, Medium
https://onepiece.fandom.com/wiki/Koala, Medium
https://onepiece.fandom.com/wiki/Borsalino, Medium
https://onepiece.fandom.com/wiki/Gaimon, Medium
https://onepiece.fandom.com/wiki/Pedro, Medium
https://onepiece.fandom.com/wiki/Monkey_D._Dragon, Medium
https://onepiece.fandom.com/wiki/Thousand_Sunny, Medium
https://onepiece.fandom.com/wiki/Bepo, Medium
https://onepiece.fandom.com/wiki/Kaidou, Medium
https://onepiece.fandom.com/wiki/Rockstar, Medium
https://onepiece.fandom.com/wiki/Hiriluk, Medium
https://onepiece.fandom.com/wiki/Rebecca, Medium
https://onepiece.fandom.com/wiki/Paulie, Medium
https://onepiece.fandom.com/wiki/Urouge, Medium
https://onepiece.fandom.com/wiki/Namur, Medium
https://onepiece.fandom.com/wiki/Senor_Pink, Medium
https://onepiece.fandom.com/wiki/Cavendish, Medium
https://onepiece.fandom.com/wiki/Gecko_Moria, Medium
https://onepiece.fandom.com/wiki/Karoo, Medium
https://onepiece.fandom.com/wiki/Monet, Medium
https://onepiece.fandom.com/wiki/Kaku, Medium
https://onepiece.fandom.com/wiki/Orlumbus, Medium
https://onepiece.fandom.com/wiki/Emporio_Ivankov, Medium
https://onepiece.fandom.com/wiki/Morgans, Medium
https://onepiece.fandom.com/wiki/Bell-m%C3%A8re, Medium
https://onepiece.fandom.com/wiki/Basil_Hawkins, Medium
https://onepiece.fandom.com/wiki/Denjiro, Medium
https://onepiece.fandom.com/wiki/Gin, Medium
https://onepiece.fandom.com/wiki/Jewelry_Bonney, Medium
https://onepiece.fandom.com/wiki/Charlotte_Linlin, Medium
https://onepiece.fandom.com/wiki/Marguerite, Hard
https://onepiece.fandom.com/wiki/Wyper, Hard
https://onepiece.fandom.com/wiki/Kung-Fu_Dugong, Extreme
https://onepiece.fandom.com/wiki/Charlotte_Mont-d%27Or, Medium
https://onepiece.fandom.com/wiki/Caesar_Clown, Medium
https://onepiece.fandom.com/wiki/Kin%27emon, Medium
https://onepiece.fandom.com/wiki/Zeff, Medium
https://onepiece.fandom.com/wiki/Vista, Medium
https://onepiece.fandom.com/wiki/Charlotte_Perospero, Medium
https://onepiece.fandom.com/wiki/Kawamatsu, Medium
https://onepiece.fandom.com/wiki/Pandaman, Extreme
https://onepiece.fandom.com/wiki/Bartholomew_Kuma, Medium
https://onepiece.fandom.com/wiki/Charlotte_Cracker, Medium
https://onepiece.fandom.com/wiki/Chouchou, Medium
https://onepiece.fandom.com/wiki/Nekomamushi, Medium
https://onepiece.fandom.com/wiki/Baby_5, Medium
https://onepiece.fandom.com/wiki/Penguin, Medium
https://onepiece.fandom.com/wiki/Kuro, Medium
https://onepiece.fandom.com/wiki/Mont_Blanc_Noland, Hard
https://onepiece.fandom.com/wiki/Farafra, Extreme
https://onepiece.fandom.com/wiki/Iceburg, Hard
https://onepiece.fandom.com/wiki/Mikita, Hard
https://onepiece.fandom.com/wiki/Laboon, Hard
https://onepiece.fandom.com/wiki/Kyros, Medium
https://onepiece.fandom.com/wiki/Vinsmoke_Niji, Medium
https://onepiece.fandom.com/wiki/Batchee, Hard
https://onepiece.fandom.com/wiki/Curly_Dadan, Hard
https://onepiece.fandom.com/wiki/Makino, Hard
https://onepiece.fandom.com/wiki/Vinsmoke_Ichiji, Medium
https://onepiece.fandom.com/wiki/King, Medium
https://onepiece.fandom.com/wiki/Gedatsu, Medium
https://onepiece.fandom.com/wiki/Kalifa, Hard
https://onepiece.fandom.com/wiki/Hannyabal, Hard
https://onepiece.fandom.com/wiki/Diesel, Hard
https://onepiece.fandom.com/wiki/Daz_Bonez, Hard
https://onepiece.fandom.com/wiki/Bellamy, Medium
https://onepiece.fandom.com/wiki/Magellan, Medium
https://onepiece.fandom.com/wiki/Higuma, Medium
https://onepiece.fandom.com/wiki/Kureha, Medium
https://onepiece.fandom.com/wiki/Page_One, Medium
https://onepiece.fandom.com/wiki/Belo_Betty, Medium
https://onepiece.fandom.com/wiki/Viola, Medium
https://onepiece.fandom.com/wiki/Kalgara, Extreme
https://onepiece.fandom.com/wiki/Sugar, Hard
https://onepiece.fandom.com/wiki/Raki, Extreme
https://onepiece.fandom.com/wiki/Foxy, Hard
https://onepiece.fandom.com/wiki/Alvida, Hard
https://onepiece.fandom.com/wiki/Ryuma, Hard
https://onepiece.fandom.com/wiki/Jabra, Hard
https://onepiece.fandom.com/wiki/Leo, Hard
https://onepiece.fandom.com/wiki/Conis, Hard
https://onepiece.fandom.com/wiki/Arlong, Medium
https://onepiece.fandom.com/wiki/Kumashi, Extreme
https://onepiece.fandom.com/wiki/Sasaki, Hard
https://onepiece.fandom.com/wiki/Vinsmoke_Yonji, Medium
https://onepiece.fandom.com/wiki/Galdino, Hard
https://onepiece.fandom.com/wiki/Queen, Medium
https://onepiece.fandom.com/wiki/Ryunosuke, Extreme
https://onepiece.fandom.com/wiki/Rocks_D._Xebec, Medium
https://onepiece.fandom.com/wiki/Nezumi, Extreme
https://onepiece.fandom.com/wiki/Nojiko, Hard
https://onepiece.fandom.com/wiki/Hina, Hard
https://onepiece.fandom.com/wiki/Tyrannosaurus, Extreme
https://onepiece.fandom.com/wiki/Shimotsuki_Yasuie, Hard
https://onepiece.fandom.com/wiki/Tom, Hard
https://onepiece.fandom.com/wiki/Kuina, Hard
https://onepiece.fandom.com/wiki/Lord_of_the_Coast, Extreme
https://onepiece.fandom.com/wiki/Thatch, Extreme
https://onepiece.fandom.com/wiki/Jaguar_D._Saul, Medium
https://onepiece.fandom.com/wiki/Fisher_Tiger, Medium
https://onepiece.fandom.com/wiki/Capone_Bege, Medium
https://onepiece.fandom.com/wiki/Hiking_Bear, Extreme
https://onepiece.fandom.com/wiki/Nico_Olvia, Hard
https://onepiece.fandom.com/wiki/Krieg, Hard
https://onepiece.fandom.com/wiki/Marianne, Extreme
https://onepiece.fandom.com/wiki/Spandam, Hard
https://onepiece.fandom.com/wiki/Gyro, Extreme
https://onepiece.fandom.com/wiki/Shachi, Hard
https://onepiece.fandom.com/wiki/Boa_Sandersonia, Extreme
https://onepiece.fandom.com/wiki/Sengoku, Medium
https://onepiece.fandom.com/wiki/Black_Maria, Medium
https://onepiece.fandom.com/wiki/Scratchmen_Apoo, Medium
https://onepiece.fandom.com/wiki/Stussy, Medium
https://onepiece.fandom.com/wiki/Kozuki_Toki, Medium
https://onepiece.fandom.com/wiki/Lucky_Roux, Medium
https://onepiece.fandom.com/wiki/T_Bone, Hard
https://onepiece.fandom.com/wiki/Maynard, Hard
https://onepiece.fandom.com/wiki/Charlotte_Smoothie, Hard
https://onepiece.fandom.com/wiki/Spencer, Extreme
https://onepiece.fandom.com/wiki/Otohime, Hard
https://onepiece.fandom.com/wiki/Mansherry, Extreme
https://onepiece.fandom.com/wiki/Kozuki_Momonosuke, Easy
https://onepiece.fandom.com/wiki/Babanuki, Extreme
https://onepiece.fandom.com/wiki/Koza, Extreme
https://onepiece.fandom.com/wiki/Kaya, Medium
https://onepiece.fandom.com/wiki/Jack, Medium
https://onepiece.fandom.com/wiki/Charlos, Medium
https://onepiece.fandom.com/wiki/Shakuyaku, Medium
https://onepiece.fandom.com/wiki/Speed, Extreme
https://onepiece.fandom.com/wiki/Mont_Blanc_Cricket, Extreme
https://onepiece.fandom.com/wiki/Toko, Hard
https://onepiece.fandom.com/wiki/Momonga, Hard
https://onepiece.fandom.com/wiki/Victoria_Cindry, Extreme
https://onepiece.fandom.com/wiki/Kurozumi_Kanjuro, Medium
https://onepiece.fandom.com/wiki/Pearl, Extreme
https://onepiece.fandom.com/wiki/Vinsmoke_Sora, Hard
https://onepiece.fandom.com/wiki/Shyarly, Extreme
https://onepiece.fandom.com/wiki/Hattori, Extreme
https://onepiece.fandom.com/wiki/Vergo, Hard
https://onepiece.fandom.com/wiki/Chimney, Extreme
https://onepiece.fandom.com/wiki/Gama_Pyonnosuke, Extreme
https://onepiece.fandom.com/wiki/Portgas_D._Rouge, Hard
https://onepiece.fandom.com/wiki/Yasopp, Medium
https://onepiece.fandom.com/wiki/Helmeppo, Medium
https://onepiece.fandom.com/wiki/Tonjit, Extreme
https://onepiece.fandom.com/wiki/Inazuma, Extreme
https://onepiece.fandom.com/wiki/Zeus, Medium
https://onepiece.fandom.com/wiki/Jango, Medium
https://onepiece.fandom.com/wiki/Karasu, Medium
https://onepiece.fandom.com/wiki/Klabautermann, Extreme
https://onepiece.fandom.com/wiki/Who%27s-Who, Hard
https://onepiece.fandom.com/wiki/Dellinger, Hard
https://onepiece.fandom.com/wiki/Camie, Hard
https://onepiece.fandom.com/wiki/Wanda, Hard
https://onepiece.fandom.com/wiki/Dalton, Hard
https://onepiece.fandom.com/wiki/Duval, Hard
https://onepiece.fandom.com/wiki/Anjo, Extreme
https://onepiece.fandom.com/wiki/Hyogoro, Hard
https://onepiece.fandom.com/wiki/Inuarashi, Medium
https://onepiece.fandom.com/wiki/Hajrudin, Medium
https://onepiece.fandom.com/wiki/Pappag, Extreme
https://onepiece.fandom.com/wiki/Rindo, Extreme
https://onepiece.fandom.com/wiki/Heracles, Hard
https://onepiece.fandom.com/wiki/Scopper_Gaban, Hard
https://onepiece.fandom.com/wiki/Sadi, Hard
https://onepiece.fandom.com/wiki/Bao_Huang, Extreme
https://onepiece.fandom.com/wiki/Charlotte_Amande, Extreme
https://onepiece.fandom.com/wiki/Monster, Extreme
https://onepiece.fandom.com/wiki/Lindbergh, Hard
https://onepiece.fandom.com/wiki/Laffitte, Hard
https://onepiece.fandom.com/wiki/Gonbe, Extreme
https://onepiece.fandom.com/wiki/Charlotte_Br%C3%BBl%C3%A9e, Hard
https://onepiece.fandom.com/wiki/Kurozumi_Orochi, Medium
https://onepiece.fandom.com/wiki/Toto, Extreme
https://onepiece.fandom.com/wiki/Zala, Extreme
https://onepiece.fandom.com/wiki/Den_Den_Mushi, Extreme
https://onepiece.fandom.com/wiki/Hatchan, Extreme
https://onepiece.fandom.com/wiki/Gladius, Extreme
https://onepiece.fandom.com/wiki/Bunbuku, Extreme
https://onepiece.fandom.com/wiki/Onimaru, Extreme
https://onepiece.fandom.com/wiki/Matsuge, Extreme
https://onepiece.fandom.com/wiki/Suu, Extreme
https://onepiece.fandom.com/wiki/Sai, Hard
https://onepiece.fandom.com/wiki/Johnny, Hard
https://onepiece.fandom.com/wiki/Nefertari_Cobra, Medium
https://onepiece.fandom.com/wiki/Crocus, Hard
https://onepiece.fandom.com/wiki/Shiryu, Hard
https://onepiece.fandom.com/wiki/Chaka, Extreme
https://onepiece.fandom.com/wiki/Wanze, Extreme
https://onepiece.fandom.com/wiki/Camel, Extreme
https://onepiece.fandom.com/wiki/Nyasha, Extreme
https://onepiece.fandom.com/wiki/Gan_Fall, Hard
https://onepiece.fandom.com/wiki/Genzo, Extreme
https://onepiece.fandom.com/wiki/Momoo, Extreme
https://onepiece.fandom.com/wiki/Nola, Extreme
https://onepiece.fandom.com/wiki/Yorki, Extreme
https://onepiece.fandom.com/wiki/Zunesha, Medium
https://onepiece.fandom.com/wiki/Jozu, Hard
https://onepiece.fandom.com/wiki/Kokoro, Hard
https://onepiece.fandom.com/wiki/Rika, Extreme
https://onepiece.fandom.com/wiki/Porche, Extreme
https://onepiece.fandom.com/wiki/Ishilly, Extreme
https://onepiece.fandom.com/wiki/Charlotte_Praline, Extreme
https://onepiece.fandom.com/wiki/South_Bird, Extreme
https://onepiece.fandom.com/wiki/Tsuru, Hard
https://onepiece.fandom.com/wiki/Charlotte_Oven, Hard
https://onepiece.fandom.com/wiki/Gerd, Extreme
https://onepiece.fandom.com/wiki/Blueno, Hard
https://onepiece.fandom.com/wiki/Wicca, Extreme
https://onepiece.fandom.com/wiki/Kamakiri, Extreme
https://onepiece.fandom.com/wiki/Pekoms, Hard
https://onepiece.fandom.com/wiki/Little_Oars_Jr., Extreme
https://onepiece.fandom.com/wiki/Trafalgar_Lami, Extreme
https://onepiece.fandom.com/wiki/Domino, Hard
https://onepiece.fandom.com/wiki/Ideo, Extreme
https://onepiece.fandom.com/wiki/Yu, Extreme
https://onepiece.fandom.com/wiki/Surume, Extreme
https://onepiece.fandom.com/wiki/Ipponmatsu, Extreme
https://onepiece.fandom.com/wiki/Haruta, Extreme
https://onepiece.fandom.com/wiki/Charlotte_Flampe, Extreme
https://onepiece.fandom.com/wiki/Tsunagoro, Extreme
https://onepiece.fandom.com/wiki/Charlotte_Galette, Extreme
https://onepiece.fandom.com/wiki/Nora_Gitsune, Extreme
https://onepiece.fandom.com/wiki/Van_Augur, Hard
https://onepiece.fandom.com/wiki/Pandawoman, Extreme
https://onepiece.fandom.com/wiki/Domo-kun_and_Nnke-kun, Extreme
https://onepiece.fandom.com/wiki/Richie, Hard
https://onepiece.fandom.com/wiki/Funkfreed, Extreme
https://onepiece.fandom.com/wiki/Shinobu, Hard
https://onepiece.fandom.com/wiki/McGuy, Extreme
https://onepiece.fandom.com/wiki/Caribou, Medium
https://onepiece.fandom.com/wiki/Boodle, Extreme
https://onepiece.fandom.com/wiki/Mocha, Extreme
https://onepiece.fandom.com/wiki/Marumieta, Extreme
https://onepiece.fandom.com/wiki/Trebol, Extreme
https://onepiece.fandom.com/wiki/Koushirou, Extreme
https://onepiece.fandom.com/wiki/Milky, Extreme
https://onepiece.fandom.com/wiki/Gatz, Extreme
https://onepiece.fandom.com/wiki/Charlotte_Lola, Hard
https://onepiece.fandom.com/wiki/Demaro_Black, Extreme
https://onepiece.fandom.com/wiki/Negikuma_Maria, Extreme
https://onepiece.fandom.com/wiki/Chicken, Extreme
https://onepiece.fandom.com/wiki/Robson, Extreme
https://onepiece.fandom.com/wiki/Mikio_Itoo, Extreme
https://onepiece.fandom.com/wiki/Aisa, Extreme
https://onepiece.fandom.com/wiki/Mero, Extreme
https://onepiece.fandom.com/wiki/Pagaya, Extreme
https://onepiece.fandom.com/wiki/Whitey_Bay, Extreme
https://onepiece.fandom.com/wiki/Pinky, Extreme
https://onepiece.fandom.com/wiki/Doma, Extreme
https://onepiece.fandom.com/wiki/Kumadori, Extreme
https://onepiece.fandom.com/wiki/Wire, Extreme
https://onepiece.fandom.com/wiki/Wapol, Medium
https://onepiece.fandom.com/wiki/Aphelandra, Extreme
https://onepiece.fandom.com/wiki/Tristan, Extreme
https://onepiece.fandom.com/wiki/Yosaku, Hard
https://onepiece.fandom.com/wiki/Salome, Extreme
https://onepiece.fandom.com/wiki/Heat, Extreme
https://onepiece.fandom.com/wiki/Tokikake, Extreme
https://onepiece.fandom.com/wiki/Suleiman, Extreme
https://onepiece.fandom.com/wiki/Donquixote_Mjosgard, Hard
https://onepiece.fandom.com/wiki/Megalo, Extreme
https://onepiece.fandom.com/wiki/Aremo_Ganmi, Extreme
https://onepiece.fandom.com/wiki/Hoe, Extreme
https://onepiece.fandom.com/wiki/Bobbin, Extreme
https://onepiece.fandom.com/wiki/Sentomaru, Medium
https://onepiece.fandom.com/wiki/Fukaboshi, Hard
https://onepiece.fandom.com/wiki/Cosette, Extreme
https://onepiece.fandom.com/wiki/Absalom, Hard
https://onepiece.fandom.com/wiki/Lao_G, Hard
https://onepiece.fandom.com/wiki/Hody_Jones, Hard
https://onepiece.fandom.com/wiki/Ashura_Doji, Hard
https://onepiece.fandom.com/wiki/Tacos, Extreme
https://onepiece.fandom.com/wiki/Lassoo, Extreme
https://onepiece.fandom.com/wiki/Kibagaeru, Extreme
https://onepiece.fandom.com/wiki/Zeo, Extreme
https://onepiece.fandom.com/wiki/Fukurou, Extreme
https://onepiece.fandom.com/wiki/Yokozuna, Extreme
https://onepiece.fandom.com/wiki/Chadros_Higelyges, Extreme
https://onepiece.fandom.com/wiki/Ninjin, Extreme
https://onepiece.fandom.com/wiki/Koyama, Extreme
https://onepiece.fandom.com/wiki/Vasco_Shot, Hard
https://onepiece.fandom.com/wiki/Igaram, Extreme
https://onepiece.fandom.com/wiki/Bellett, Extreme
https://onepiece.fandom.com/wiki/Shishilian, Extreme
https://onepiece.fandom.com/wiki/Sarahebi, Extreme
https://onepiece.fandom.com/wiki/Wadatsumi, Extreme
https://onepiece.fandom.com/wiki/Doc_Q, Medium
https://onepiece.fandom.com/wiki/Moda, Extreme
https://onepiece.fandom.com/wiki/Turco, Extreme
https://onepiece.fandom.com/wiki/Michael_and_Hoichael, Extreme
https://onepiece.fandom.com/wiki/Attach, Extreme
https://onepiece.fandom.com/wiki/Jesus_Burgess, Medium
https://onepiece.fandom.com/wiki/Brogy, Medium
https://onepiece.fandom.com/wiki/Morgan, Hard
https://onepiece.fandom.com/wiki/Vito, Extreme
https://onepiece.fandom.com/wiki/Tsurujo, Extreme
https://onepiece.fandom.com/wiki/Charlotte_Daifuku, Extreme
https://onepiece.fandom.com/wiki/Clover, Extreme
https://onepiece.fandom.com/wiki/Morley, Hard
https://onepiece.fandom.com/wiki/Raizo, Medium
https://onepiece.fandom.com/wiki/Scarlett, Extreme
https://onepiece.fandom.com/wiki/Nero, Extreme
https://onepiece.fandom.com/wiki/Komachiyo, Extreme
https://onepiece.fandom.com/wiki/Drip, Extreme
https://onepiece.fandom.com/wiki/Faust, Extreme
https://onepiece.fandom.com/wiki/Haredas, Extreme
https://onepiece.fandom.com/wiki/Pound, Extreme
https://onepiece.fandom.com/wiki/Cabaji, Hard
https://onepiece.fandom.com/wiki/Oars, Hard
https://onepiece.fandom.com/wiki/Pankuta_Dakeyan, Extreme
https://onepiece.fandom.com/wiki/Happa_Yamao, Extreme
https://onepiece.fandom.com/wiki/Mr._9, Extreme
https://onepiece.fandom.com/wiki/Pierre, Extreme
https://onepiece.fandom.com/wiki/Tamago, Extreme
https://onepiece.fandom.com/wiki/Smiley, Extreme
https://onepiece.fandom.com/wiki/Vander_Decken_IX, Hard
https://onepiece.fandom.com/wiki/Hotori_and_Kotori, Extreme
https://onepiece.fandom.com/wiki/Vinsmoke_Judge, Medium
https://onepiece.fandom.com/wiki/Ripper, Extreme
https://onepiece.fandom.com/wiki/Sanjuan_Wolf, Hard
https://onepiece.fandom.com/wiki/Hikoichi, Extreme
https://onepiece.fandom.com/wiki/Blamenco, Extreme
https://onepiece.fandom.com/wiki/Edward_Weevil, Hard
https://onepiece.fandom.com/wiki/Mohji, Hard
"""

lines = data.split("\n")
lines = [line for line in lines if line.strip() != ""]

characters = []
for line in lines:
    url, difficulty = line.split(", ")
    character = {
        "url": url,
        "difficulty": difficulty
    }
    characters.append(character)

with open("opwikilinksdifficulty.json", "w") as file:
    json.dump(characters, file, indent=4)
